discord_bot:
  token: TOKEN_HERE
  default_prefix: a.
  owner_ids: [896817060489883688]

bs_servers:
  path: ../
  folders:
    Abyss - Teams: '0'
    Abyss - FFA Fun Games: '1'
    Abyss - FFA Epic Elimination: '2'
  players_stats_file: /dist/ba_data/python/mod/data/player/stats.json
